var disclaimers = ["Hey, I haven't obscured this at all, so welcome to the code.",
 "Should you take issue with any of these lines, once you pair them up, please let me know and I'll point you in direction of the source",
"I kept these mostly gender-neutral but there's a general male-speaking-to-female dynamic so watch out, don't put all your hopes in this basket"];
var setups = ['Are you my little toe?',
'Are you heroin?',
'Is your name Luke?',
'I think . . . C7?',
"Are you not-sand?",
'Please have sex with me?',
'Have you heard of "Imagine Dragons"?',
'Hey, want some updog?',
"How much does a polar bear weigh?",
"Don't you agree, pens should be like women?",
"Bags should be like women.",
"Are you a toaster?",
'Are you the happiness I experienced as a child?',
'Are you an enemy insurgent?',
'Are you happiness and peace?',
"Was your father Boreas, god of the north wind?",
"Are you my appendix?",
"Are you a dinosaur? ",
"Can I treat you like a princess?",
"Are you the sun?",
"If I said you had a lovely body would you be offended?",
"You a fan of big dicks?",
"Wanna know why I like you?",
"I like to roleplay as bulky -",
"Our love knows no bounds - you go? I go! You stay? I stay! You get locked alone on an island inside a tower?",
"Are you Modern Art?",
"Are you a Jackson Pollock?",
"Have I ever told you about my limbo skills?",
"Have you got 10 toes?",
"Did it hurt?",
"You look so much like my first wife -",
"I was emotionally neglected as a child, but guess what?",
"You're so adorable, I just want to spoil you!",
"Are you an emergency endoscopy?",
"Was your father a thief?",
"Was your mother a seamstress?",
'Are you a sudden and painless death?',
"You wanna roleplay?",
"Do you believe in the supernatural?"
]
var responses = ['Because I want to bang you on all my furniture',
"Because despite everything I've been told, I wanna do you",
"Because I'm your daddy",
"Oh sorry, I thought this was a vending machine - because you're a snack!",
"Because I don't not like you. You're not coarse and not rough and not irritating and don't get everywhere",
"I'm very lonely and you're so attractive",
"Imagine draggin' these balls across your face",
"Nothing much dog, what's up with you?",
"Not enough to break the ice - if they did weigh that much they'd be in trouble",
"Disposable.",
"Simple and with one lockable opening",
"Because get in my bath!",
"Because I miss you so bad",
"Because I want to take you out",
"Because I need you inside me",
"Cos you've blown me away",
"Because you're gonna make me burst",
"Because I'll dig you out and polish you no matter how old you are",
"Because I really need to shore up my alliance with France",
"Because you're bright and that's important to me",
"Would you hold it against me?",
"Then you'll love my personality but hate my actual dick",
"Because you're how I like my coffee - thick and creamy",
"Tonight I'll be Mike Tyson, tomorrow you'll be Thor",
"I turn into a shower of magical rain and knock you up!",
"Because I don't understand you but I can still admire you",
"Because you're a mess but I get it, heck I even like it",
"No matter how low the bar, I'll be underneath it",
"That's how many toes I have! Snap!",
"When you stole an angel's face and put it on your face so it was like your face?",
"I've never married",
"It makes me a terrible partner, so you should ditch me and I'll see a therapist",
"Just sit somewhere warm and moist and I'll forget about you",
"Because it's vital you get up in my guts",
"I'm afraid I have to inform the police about that",
"Because you're cute as a button",
'Because I fantasise about you constantly',
"You can be a noble and beautiful maiden and I'll be a rugged stablehand that you fire for getting overfamiliar.",
"Because I'm definitely gonna ghost you."
]


function newQuote() {
  var rand1 = Math.floor(Math.random()*(setups.length));
  var rand2 = Math.floor(Math.random()*(setups.length-1));
  if (rand2 >= rand1){
      rand2+=1;
  }
  document.getElementById('quoteSetup').innerHTML = setups[rand1];
  document.getElementById('quoteResponse').innerHTML = responses[rand2];
}
